# Generated by Django 3.2.5 on 2021-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(default='Заголовок отсутвует', max_length=124),
        ),
    ]
