# Generated by Django 3.2.6 on 2021-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(default='Заголовок отсутвует', max_length=512),
        ),
    ]
